name: CI

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
  
    # Instala CMake 3.16 manualmente
    - name: Install CMake 3.16
      run: |
        curl -LO https://github.com/Kitware/CMake/releases/download/v3.16.9/cmake-3.16.9-Darwin-x86_64.tar.gz
        tar -xzf cmake-3.16.9-Darwin-x86_64.tar.gz
        echo "$PWD/cmake-3.16.9-Darwin-x86_64/bin" >> $GITHUB_PATH
        cmake --version
  
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v3
      with:
        path: "vulkansdk-macos-1.2.162.0"
        key: vulkansdk-macos-1.2.162.0
  
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.2.162.0/mac/vulkansdk-macos-1.2.162.0.dmg?Human=true -O vulkansdk-macos-1.2.162.0.dmg
        hdiutil attach vulkansdk-macos-1.2.162.0.dmg
        cp -r /Volumes/vulkansdk-macos-1.2.162.0 .
        rm -rf vulkansdk-macos-1.2.162.0/Applications
        find vulkansdk-macos-1.2.162.0 -type f | grep -v -E 'vulkan|glslang|MoltenVK' | xargs rm
        hdiutil detach /Volumes/vulkansdk-macos-1.2.162.0
  
    - name: build-x86_64
      run: |
        export VULKAN_SDK=`pwd`/vulkansdk-macos-1.2.162.0/macOS
        mkdir build-x86_64 && cd build-x86_64
        cmake -DUSE_STATIC_MOLTENVK=ON \
              -DCMAKE_OSX_ARCHITECTURES="x86_64" \
              -DVulkan_INCLUDE_DIR=`pwd`/../vulkansdk-macos-1.2.162.0/MoltenVK/include \
              -DVulkan_LIBRARY=`pwd`/../vulkansdk-macos-1.2.162.0/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64/libMoltenVK.a \
              ../src -DCMAKE_POLICY_VERSION_MINIMUM=3.5
        cmake --build . -j 3
  
    - name: build-arm64
      run: |
        export VULKAN_SDK=`pwd`/vulkansdk-macos-1.2.162.0/macOS
        mkdir build-arm64 && cd build-arm64
        cmake -DUSE_STATIC_MOLTENVK=ON \
              -DCMAKE_OSX_ARCHITECTURES="arm64" \
              -DVulkan_INCLUDE_DIR=`pwd`/../vulkansdk-macos-1.2.162.0/MoltenVK/include \
              -DVulkan_LIBRARY=`pwd`/../vulkansdk-macos-1.2.162.0/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64/libMoltenVK.a \
              ../src -DCMAKE_POLICY_VERSION_MINIMUM=3.5
        cmake --build . -j 3
