name: CI

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install old CMake
        run: |
          brew uninstall cmake || true
          brew install cmake@3.16
          echo "$(brew --prefix cmake@3.16)/bin" >> $GITHUB_PATH

      - name: Cache Vulkan SDK
        uses: actions/cache@v4
        with:
          path: vulkansdk
          key: VulkanSDK-1.3.280.0-macos

      - name: Install Vulkan SDK
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.3.280.0/mac/vulkansdk-macos-1.3.280.0.dmg -O sdk.dmg
          hdiutil attach sdk.dmg
          cp -r /Volumes/vulkansdk-macos-* vulkansdk
          hdiutil detach /Volumes/vulkansdk-macos-*

      - name: Build x86_64
        run: |
          export VULKAN_SDK=$PWD/vulkansdk/macOS
          cmake -S src -B build-x86 \
            -DCMAKE_OSX_ARCHITECTURES="x86_64" \
            -DUSE_STATIC_MOLTENVK=ON \
            -DVulkan_INCLUDE_DIR=$PWD/vulkansdk/MoltenVK/include \
            -DVulkan_LIBRARY=$PWD/vulkansdk/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64/libMoltenVK.a
          cmake --build build-x86 --parallel

      - name: Build arm64
        run: |
          export VULKAN_SDK=$PWD/vulkansdk/macOS
          cmake -S src -B build-arm \
            -DCMAKE_OSX_ARCHITECTURES="arm64" \
            -DUSE_STATIC_MOLTENVK=ON \
            -DVulkan_INCLUDE_DIR=$PWD/vulkansdk/MoltenVK/include \
            -DVulkan_LIBRARY=$PWD/vulkansdk/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64/libMoltenVK.a
          cmake --build build-arm --parallel
